### ISSUE TITLE
Broken Links in Documentation

### ISSUE THREAD

**Issue by CannonLock** [ncsa/oa4mp#104]
Found many broken links in the documentation. Rather then record an incomplete list of the ones I hit I just ran my link checker, which found 400 errors.

Note, the link checker is far from perfect so you will find some false negatives and duplicates if the break is in the commonly used element.

[oa4mp-doc=link-test.log](https://github.com/ncsa/oa4mp/files/11725852/oa4mp-doc.link-test.log)

**Comment by jjg-123** [comment]
A lot of these are auto-generated by Maven. Manually tracking over 1000  down is not going to happen. Many more are because the java doc is not being generated quite right. Opening another issue on fixing the javadoc.
