### ISSUE TITLE
Getting Started guide needs updating for OIDC

### ISSUE THREAD

**Issue by jbasney** [ncsa/OA4MP#11]
http://grid.ncsa.illinois.edu/myproxy/oauth/server/manuals/getting-started.xhtml needs updating for OIDC. It contains a broken link to https://svn.code.sf.net/p/cilogon/code/tags/edu.uiuc.ncsa/myproxy-3.5/oa4mp-webapp and points to http://svn.code.sf.net/p/cilogon/code/tags/latest/server/oauth.war (OAuth 1) rather than the recommended http://svn.code.sf.net/p/cilogon/code/tags/latest/server/oauth2.war (OIDC).

**Comment by jjg-123** [comment]
All documentation has been moved. http://grid.ncsa.illinois.edu/myproxy/oauth can reasonably go away at some point.
