### ISSUE TITLE
allow users to view and revoke tokens

### ISSUE THREAD

**Issue by jbasney** [ncsa/OA4MP#12]
I don't think there's an OAuth or OIDC standard for this, but it's common for OAuth providers to give the user a page to view a list of active tokens with the ability to revoke them. https://myaccount.google.com/permissions is one example.

I expect this functionality would only be supported for servers that use REMOTE_USER authentication so the user can authenticate to view their tokens.

**Comment by jjg-123** [comment]
There are now both introspection and revocation endpoints in OA4MP as of version 5.
