### ISSUE TITLE
Add elliptic curve support

### ISSUE THREAD

**Issue by jjg-123** [ncsa/oa4mp#131]
OA4MP should support signing tokens with Elliptic curve algorithms, mostly compliant with https://datatracker.ietf.org/doc/html/rfc8422 and https://datatracker.ietf.org/doc/html/rfc8446. These are big specs, so not all of them should be implemented, "just enough."

**Comment by jbasney** [comment]
I think the need is to support `"alg": "ES256"` per https://www.rfc-editor.org/rfc/rfc7518.html#section-3.4 .
