### ISSUE TITLE
Scopes in response from token endpoint only includes scopes for the id token. Include all scopes

### ISSUE THREAD

**Issue by jjg-123** [ncsa/oa4mp#134]
The response to the token exchange must include the scope claim if the scopes returned are not the same as the original request. What should be returned as per https://www.rfc-editor.org/rfc/rfc6749#section-5.1:
```
scope
         OPTIONAL, if identical to the scope requested by the client;
         otherwise, REQUIRED.  The scope of the access token as
         described by [Section 3.3](https://www.rfc-editor.org/rfc/rfc6749#section-3.3).

```         

but then it refers to section 3.3 (https://www.rfc-editor.org/rfc/rfc6749#section-3.3) where it promptly states 

```
The authorization and token endpoints allow the client to specify the
   scope of the access request using the "scope" request parameter.
```         
   
   
which seems to imply not the access token, but all scopes. for access (which includes access to user meta data as per the id token.) This is important since the former seems to limit the response to just the access token itself, but the latter seems to imply all access.

PS. Refresh tokens may also be JWTs and in theory can have scopes as well. For now we will ignore that possibility.

**_Executive  decision:_** It means all scopes for both the access token and the id token. 

This requires some digging since these may be buried inside the access token that has been liberally massaged by QDL, hence must be discovered and returned.

PS. refresh tokens may in theory have scopes as well. We will ignore this possibility for now.

**Comment by msalle** [comment]
note that pure OAuth2 (RFC6749) doesn't have ID tokens. But indeed, the OAuth2 protected resource in OIDC is the userinfo endpoint, to which you get access as client via the `openid` scope and additional scopes such as `profile` etc.
