### ISSUE TITLE
proxy_claims stopped working in 5.4.1

### ISSUE THREAD

**Issue by bbockelm** [ncsa/oa4mp#137]
After upgrading to 5.4.1, the `proxy_claims.` stem is no longer filled in for my QDL scripts, meaning that my issuer has largely stopped working.

Potentially this commit might be the culprit: https://github.com/ncsa/oa4mp/commit/fc61649c40d82b9edb9f24c1904a3d2f8b972175 ?

**Comment by bbockelm** [comment]
Have confirmed that a downgrade back to 5.3.1 solves this issue.

**Comment by jjg-123** [comment]
This was a side effect of https://github.com/ncsa/oa4mp/issues/130, where the structure of the ID token object was changed but the code to read it from the client was not updated.
