### ISSUE TITLE
Support OAuth Resource Indicators

### ISSUE THREAD

**Issue by jbasney** [ncsa/OA4MP#14]
New draft proposing a method for the client to signal the audience(s) that it wants for the token:

https://tools.ietf.org/html/draft-ietf-oauth-resource-indicators-00

>    Several years of deployment and implementation experience with OAuth
>   2.0 [RFC6749] has uncovered a need, in some circumstances, for the
>   client to explicitly signal to the authorization sever where it
>   intends to use the access token it is requesting.

**Comment by jjg-123** [comment]
Done. This will be deployed on surge in the next round of server/client updates.
