### ISSUE TITLE
Unused client cleanup deleting in-use clients

### ISSUE THREAD

**Issue by bbockelm** [ncsa/oa4mp#156]
In the `scitokens-oauth2-server` [default configuration](https://github.com/scitokens/scitokens-oauth2-server/blob/master/scitokens-server/etc/server-config.xml.tmpl#L21-L28), we have the following:

```
        <unusedClientCleanup gracePeriod="6 hr"
                             deleteVersions="false"
                             enabled="true"
                             interval="4 hr">
          <whitelist>
             <clientID>localhost:template</clientID>
          </whitelist>
        </unusedClientCleanup>
```

The intent of this block is "if there is a client that has _never_ been used, then delete it from the database".  However, after testing, it appears that this simply deletes the clients after 6 hours (potentially it's after 6 hours of no use?).

**Comment by jjg-123** [comment]
Superceded by Upkeep facility
