### ISSUE TITLE
Remove sign-artifacts from defaultGoal in pom.xml

### ISSUE THREAD

**Issue by jbasney** [ncsa/OA4MP#16]
The https://travis-ci.org/ncsa/OA4MP build fails with
```
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project myproxy: Exit code: 2 
```

I think it's because sign-artifacts is in defaultGoal in https://github.com/ncsa/OA4MP/blob/master/pom.xml.

To fix this error, please make sign-artifacts a separate build step, so the default build doesn't require a GPG setup.

**Comment by jjg-123** [comment]
Yanked. This was required for uploading to maven but we don't do that any longer so there is no reason to sign these. It can all be re-enabled if needed.
