### ISSUE TITLE
openid should be the only default scope

### ISSUE THREAD

**Issue by jbasney** [ncsa/OA4MP#17]
http://grid.ncsa.illinois.edu/myproxy/oauth/common/configuration/scopes.xhtml says that all the following scopes are requested by default: openid+email+profile+org.cilogon.userinfo+edu.uiuc.ncsa.myproxy.getcert

However, from a privacy and data minimization standpoint, only the openid scope should be requested by default.

Also, a vanilla OA4MP server will reject a request for the org.cilogon.userinfo scope, since that's CILogon-specific, so a vanilla OA4MP client shouldn't be requesting it by default.

**Comment by jjg-123** [comment]
This link is active but not really used. The actual updated document is here:

https://cilogon.github.io/oa4mp/common/configuration/scopes.html

The default is that no scopes are requested.
