### ISSUE TITLE
Incorrect type name listed in claim source documentation

### ISSUE THREAD

**Issue by bbockelm** [ncsa/oa4mp#179]
In the [claim source PDF](https://oa4mp.org/pdf/creating_claim_sources2.pdf), it says that the HTTP header source is of type `header`.

However, [in the code](https://github.com/ncsa/oa4mp/blob/master/server-loader/src/main/java/edu/uiuc/ncsa/myproxy/oa4mp/qdl/claims/CSConstants.java#L27), the name of the type is `http`.

**Comment by jjg-123** [comment]
Updated in documentation. Will deploy later.
