### ISSUE TITLE
support OAuth 2.0 Multiple Response Type Encoding Practices

### ISSUE THREAD

**Issue by jbasney** [ncsa/OA4MP#5]
Handle response_mode=form_post and other response_mode cases (i.e., query, which is the default, and fragment, which uses "#" instead of "?") as described in [OAuth 2.0 Multiple Response Type Encoding Practices](http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes).

This was an issue in CILogon PHP code, found when integrating with MediaWiki, and presumably could also be an issue for other OA4MP setups

**Comment by jjg-123** [comment]
Added.
