### ISSUE TITLE
Support Public Clients

### ISSUE THREAD

**Issue by jbasney** [ncsa/OA4MP#8]
To support clients like kubernetes kubectl (see https://github.com/kubernetes/kubernetes/issues/37874), OA4MP should support the option to register Public Clients. As documented at http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication, a Public Client does not authenticate itself at the Token Endpoint.

OA4MP MUST validate redirection URIs for public clients according to https://tools.ietf.org/html/rfc6749#section-10.6. I think OA4MP is already doing that for all clients.

Public Clients should have limited token scope (https://tools.ietf.org/html/rfc6819#section-5.1.5.1). For OA4MP, I think they should be limited to the openid scope, and not have access to the getcert, email, profile, or other scopes.

**Comment by jjg-123** [comment]
Verified that public clients have restricted scope to openid (as in, no matter what they request, only accept openid and if that is missing the request is rejected). After that, all other checks (inclduing callbacks) are verified as per any other client
