### ISSUE TITLE
Have an "atime" equivalent for clients

### ISSUE THREAD

**Issue by bbockelm** [ncsa/oa4mp#80]
On the OSG Slack, there was good discussion about reasonable protections that could be added for dynamically-registered clients.

One idea proposed was to be able to implement reasonable garbage collection of clients.  Particularly, the thinking was:

1.  Garbage collect a dynamic client after 2 hours if it's *never* been used as part of a successful flow.
2.  Garbage collect a dynamic client 60 days after its last successful flow.

Now, I don't think we need to implement such early-stage ideas.  *However*, if I were to implement them out-of-band via a script, the script would need to know, for a given client, when the last successful flow occurred -- think of it as an `atime` equivalent to the existing `last-modified-time` attribute currently saved in the client config.

Could we add such a field?  Obviously, we'd need to do the same sort of tricks as Linux does for filesystem atime (such as only persisting this information once an hour).

If it's prohibitively difficult to add this information, is there something specific we can look for in the logs such that a script could generate an `atime` database from the logs themselves?

**Comment by jjg-123** [comment]
Doing an update to clients for every access time is going to really hammer the database. One possibility that I can see is to cache access times and have a thread that mass updates them every hour or two.
