### ISSUE TITLE
Dynamic Client registration has incorrect HTTP status code

### ISSUE THREAD

**Issue by bbockelm** [ncsa/OA4MP#84]
On creation, RFC 7591 states the server responds with an HTTP 201 (Created).  OA4MP is currently returning HTTP 200 (OK).  At least in the client library I'm using, the corresponding client is rejected as it's the incorrect status.

**Comment by jjg-123** [comment]
Note that OA4MP returns 201 now, but CILogon will return 200 until the next release.
