### ISSUE TITLE
Option to not forward scopes to via proxy

### ISSUE THREAD

**Issue by bbockelm** [ncsa/OA4MP#86]
The proxy mode to CILogon for device flow defaults to passing along all the scopes in the token request to CILogon:

```
        InputLine inputLine = new InputLine("set_param", OA2CLCCommands.SHORT_REQ_PARAM_SWITCH, OA2Constants.SCOPE, scopesToString(t));
        debugger.trace(ProxyUtils.class, "getProxyUserCode input line=" + inputLine);
        clcCommands.set_param(inputLine);
```

In my case, this is wrong -- I want only the default `openid` scope that is set in the proxy OAuth2 client (in the `proxy-config.xml` file).  The "real" client is requesting a number of WLCG scopes which, of course, isn't recognized by CILogon.

From CILogon's response, I will decide on which scopes to approve.

Can we either remove these lines or make it a configuration option?

**Comment by jjg-123** [comment]
(Back from a week of back to back flu then covid. Sorry about the delay) This morphed into https://jira.ncsa.illinois.edu/browse/CIL-1584. Result is that the client now has two new properties.

  *  forward_scopes_to_proxy (boolean) if true forwards the scopes in the request to the proxy server.

  *  proxy_request_scopes list of scopes. The intersection of these and the scopes registered by the proxy client to the proxy server are requested. Note that this assumes forward_scopes_to_proxy == false.

If you use the CLI, then these are available there. Note that you cannot set them in the Client management API with an anonymous client.

These are in GIT, but are as yet not deployed, so if you have any suggestions or comments, feel free to make them.

Thanks!

Jeff
