### ISSUE TITLE
INI parser cannot handle `\`

### ISSUE THREAD

**Issue by bbockelm** [ncsa/OA4MP#88]
My LDAP password is of the form `prefix\Rpost`  (that is, some prefix characters, a `\` character, a `R`, and then some more characters).

I have an INI file parsed by QDL that looks like the following:

```
# cat /opt/secrets/cilogon_ldap_password.ini 
[prod]
server := 'ldap.example.com';
port := '636';
name := 'uid=readonly,ou=system,dc=example,dc=com';
password := 'prefix\\Rpost';
search_base := 'dc=example,dc=com';
```

When parsed as the above in a QDL script with the following line:

```
  ini. := file_read('/opt/secrets/cilogon_ldap_password.ini', 2).'prod';
```

Then the password posted is equivalent to: `prefix\\Rpost`; this causes the LDAP server to reject the credential as the LDAP server receives a password with two `\` characters instead of one `\`.  I verified from the trace output the password sent to the LDAP server is like this:

```
  "password": "prefix\\\\Rpost",
```

OTOH, if I do not escape, having a line like in the INI file:

```
password := 'prefix\Rpost';
```

then the INI file has a syntax error according to the parser:

```
Error reading file '/opt/secrets/cilogon_ldap_password.ini'unkown type
```

Note, if I put the password directly in the QDL file:

```
  ldap_cfg.password           := 'prefix\\Rpost';
```

with the `\\` in order to escape things, all is well.  The LDAP server receives a password with a single `\` character.

So, it seems there's a problem with the INI parser -- one `\` in the file is too few, two `\` is too many.

This is with OA4MP 5.2.9.0 plus posted QDL jars.

**Comment by jjg-123** [comment]
Fixed and it will be in the next release. Other options are to use YAML, HOCON, XML, QDL or  JSON for the configuration.  These are documented in [converters](https://cilogon.github.io/qdl/docs/pdf/xml-extension.pdf) You can load support for these with 
```
  module_import(module_load(info().lib.convert));
convert
  )funcs -m
yaml_in yaml_out hocon_in hocon_out qdl_in qdl_out xml_in xml_out

```
If you wanted to use YAML instead in the file /opt/secrets/cilogon_ldap_password.yaml 

```
prod:
  server: ldap.example.com
  password: prefix\Rpost
  port: '636'
  name: 'uid=readonly,ou=system,dc=example,dc=com'
  search_base: 'dc=example,dc=com'

```

you would use

`  ini. := yaml_in(file_read('/opt/secrets/cilogon_ldap_password.ini'));
`

**Comment by bbockelm** [comment]
Ah, did not know YAML was an option!  I'll try that.

In the meantime, I'm doing something horrendous with `sed` to inject the secret directly into YAML which is definitely not fun.
